# Generated by Django 4.2.5 on 2023-09-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leitores',
            new_name='Leitor',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(default='2023-09-04'),
            preserve_default=False,
        ),
    ]
